/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import javax.swing.ImageIcon;
import view.ViewCadastroCondominio;
import AppPackage.AnimationClass.*;
 
public class ViewPainelCentral extends javax.swing.JFrame {

    /**
     * Creates new form ViewCadastrarConta
     */
    public ViewPainelCentral() {
        
        initComponents();
        setLocationRelativeTo(null);
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuCondominio = new javax.swing.JMenu();
        mnuItemCadastroCondominio = new javax.swing.JMenuItem();
        mnuItemCadastroUnidade = new javax.swing.JMenuItem();
        mnuInquilino = new javax.swing.JMenu();
        mnuItemCadastroInquilino = new javax.swing.JMenuItem();
        mnuCondomino = new javax.swing.JMenu();
        mnuItemCadastroCondomino = new javax.swing.JMenuItem();
        mnuFuncionario = new javax.swing.JMenu();
        mnuItemCadatroFuncionario = new javax.swing.JMenuItem();
        mnuRelatorio = new javax.swing.JMenu();
        mnuItemFuncRel = new javax.swing.JMenuItem();
        mnuSegurança = new javax.swing.JMenu();
        mnuItemPerfil = new javax.swing.JMenuItem();
        mnuConfiguracoes = new javax.swing.JMenu();
        mnuSobre = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        jLabel3.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        jLabel3.setText("Condomínio Fácil");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setMaximumSize(new java.awt.Dimension(840, 472));
        setMinimumSize(new java.awt.Dimension(840, 472));
        setName("Home"); // NOI18N
        setSize(new java.awt.Dimension(840, 472));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jMenuBar1.setBackground(new java.awt.Color(5, 99, 103));
        jMenuBar1.setForeground(new java.awt.Color(5, 99, 103));
        jMenuBar1.setBorderPainted(false);
        jMenuBar1.setMinimumSize(new java.awt.Dimension(56, 40));
        jMenuBar1.setName("[80, 21]"); // NOI18N
        jMenuBar1.setPreferredSize(new java.awt.Dimension(80, 21));

        mnuCondominio.setBackground(new java.awt.Color(5, 99, 103));
        mnuCondominio.setBorder(new javax.swing.border.MatteBorder(null));
        mnuCondominio.setForeground(java.awt.Color.white);
        mnuCondominio.setText("Condomínio");
        mnuCondominio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mnuCondominio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mnuCondominio.setMargin(new java.awt.Insets(10, 0, 0, 0));
        mnuCondominio.setMinimumSize(null);
        mnuCondominio.setPreferredSize(new java.awt.Dimension(90, 50));
        mnuCondominio.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        mnuCondominio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuCondominioMouseClicked(evt);
            }
        });
        mnuCondominio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCondominioActionPerformed(evt);
            }
        });

        mnuItemCadastroCondominio.setBackground(new java.awt.Color(5, 99, 103));
        mnuItemCadastroCondominio.setForeground(java.awt.Color.white);
        mnuItemCadastroCondominio.setText("Cadastro de Condomínio");
        mnuItemCadastroCondominio.setActionCommand("Cadastrar");
        mnuItemCadastroCondominio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuItemCadastroCondominioMouseClicked(evt);
            }
        });
        mnuItemCadastroCondominio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemCadastroCondominioActionPerformed(evt);
            }
        });
        mnuCondominio.add(mnuItemCadastroCondominio);

        mnuItemCadastroUnidade.setBackground(new java.awt.Color(5, 99, 103));
        mnuItemCadastroUnidade.setForeground(java.awt.Color.white);
        mnuItemCadastroUnidade.setText("Cadastro de Unidade");
        mnuItemCadastroUnidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemCadastroUnidadeActionPerformed(evt);
            }
        });
        mnuCondominio.add(mnuItemCadastroUnidade);

        jMenuBar1.add(mnuCondominio);

        mnuInquilino.setBackground(new java.awt.Color(5, 99, 103));
        mnuInquilino.setBorder(new javax.swing.border.MatteBorder(null));
        mnuInquilino.setForeground(java.awt.Color.white);
        mnuInquilino.setText("Inquilino");
        mnuInquilino.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mnuInquilino.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mnuInquilino.setMargin(new java.awt.Insets(10, 0, 0, 0));
        mnuInquilino.setPreferredSize(new java.awt.Dimension(80, 40));
        mnuInquilino.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        mnuInquilino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuInquilinoActionPerformed(evt);
            }
        });

        mnuItemCadastroInquilino.setBackground(new java.awt.Color(5, 99, 103));
        mnuItemCadastroInquilino.setForeground(java.awt.Color.white);
        mnuItemCadastroInquilino.setText("cadastro inquilino");
        mnuItemCadastroInquilino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemCadastroInquilinoActionPerformed(evt);
            }
        });
        mnuInquilino.add(mnuItemCadastroInquilino);

        jMenuBar1.add(mnuInquilino);

        mnuCondomino.setBackground(new java.awt.Color(5, 99, 103));
        mnuCondomino.setBorder(new javax.swing.border.MatteBorder(null));
        mnuCondomino.setForeground(java.awt.Color.white);
        mnuCondomino.setText("Condômino");
        mnuCondomino.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mnuCondomino.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mnuCondomino.setMargin(new java.awt.Insets(10, 0, 0, 0));
        mnuCondomino.setPreferredSize(new java.awt.Dimension(90, 40));
        mnuCondomino.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        mnuItemCadastroCondomino.setBackground(new java.awt.Color(5, 99, 103));
        mnuItemCadastroCondomino.setForeground(java.awt.Color.white);
        mnuItemCadastroCondomino.setText("Cadastro condômino");
        mnuItemCadastroCondomino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemCadastroCondominoActionPerformed(evt);
            }
        });
        mnuCondomino.add(mnuItemCadastroCondomino);

        jMenuBar1.add(mnuCondomino);

        mnuFuncionario.setBackground(new java.awt.Color(5, 99, 103));
        mnuFuncionario.setBorder(new javax.swing.border.MatteBorder(null));
        mnuFuncionario.setForeground(java.awt.Color.white);
        mnuFuncionario.setText("Funcionário");
        mnuFuncionario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mnuFuncionario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mnuFuncionario.setMargin(new java.awt.Insets(10, 0, 0, 0));
        mnuFuncionario.setPreferredSize(new java.awt.Dimension(90, 40));
        mnuFuncionario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        mnuFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuFuncionarioActionPerformed(evt);
            }
        });

        mnuItemCadatroFuncionario.setBackground(new java.awt.Color(5, 99, 103));
        mnuItemCadatroFuncionario.setForeground(java.awt.Color.white);
        mnuItemCadatroFuncionario.setText("cadastro funcionario");
        mnuItemCadatroFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemCadatroFuncionarioActionPerformed(evt);
            }
        });
        mnuFuncionario.add(mnuItemCadatroFuncionario);

        jMenuBar1.add(mnuFuncionario);

        mnuRelatorio.setBackground(new java.awt.Color(5, 99, 103));
        mnuRelatorio.setBorder(new javax.swing.border.MatteBorder(null));
        mnuRelatorio.setForeground(java.awt.Color.white);
        mnuRelatorio.setText("Relatório");
        mnuRelatorio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mnuRelatorio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mnuRelatorio.setMargin(new java.awt.Insets(10, 0, 0, 0));
        mnuRelatorio.setPreferredSize(new java.awt.Dimension(90, 40));
        mnuRelatorio.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        mnuItemFuncRel.setBackground(new java.awt.Color(5, 99, 103));
        mnuItemFuncRel.setForeground(java.awt.Color.white);
        mnuItemFuncRel.setText("Relatório de Funcionário");
        mnuItemFuncRel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemFuncRelActionPerformed(evt);
            }
        });
        mnuRelatorio.add(mnuItemFuncRel);

        jMenuBar1.add(mnuRelatorio);

        mnuSegurança.setBackground(new java.awt.Color(5, 99, 103));
        mnuSegurança.setBorder(new javax.swing.border.MatteBorder(null));
        mnuSegurança.setForeground(java.awt.Color.white);
        mnuSegurança.setText("Segurança");
        mnuSegurança.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mnuSegurança.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mnuSegurança.setMargin(new java.awt.Insets(10, 0, 0, 0));
        mnuSegurança.setPreferredSize(new java.awt.Dimension(90, 40));
        mnuSegurança.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        mnuItemPerfil.setBackground(new java.awt.Color(5, 99, 103));
        mnuItemPerfil.setForeground(java.awt.Color.white);
        mnuItemPerfil.setText("Perfil");
        mnuItemPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemPerfilActionPerformed(evt);
            }
        });
        mnuSegurança.add(mnuItemPerfil);

        jMenuBar1.add(mnuSegurança);

        mnuConfiguracoes.setBackground(new java.awt.Color(5, 99, 103));
        mnuConfiguracoes.setBorder(new javax.swing.border.MatteBorder(null));
        mnuConfiguracoes.setForeground(java.awt.Color.white);
        mnuConfiguracoes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mnuConfiguracoes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mnuConfiguracoes.setLabel("Configurações");
        mnuConfiguracoes.setMargin(new java.awt.Insets(10, 0, 0, 0));
        mnuConfiguracoes.setPreferredSize(new java.awt.Dimension(110, 40));
        mnuConfiguracoes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jMenuBar1.add(mnuConfiguracoes);

        mnuSobre.setBackground(new java.awt.Color(5, 99, 103));
        mnuSobre.setBorder(new javax.swing.border.MatteBorder(null));
        mnuSobre.setForeground(java.awt.Color.white);
        mnuSobre.setText("Sobre");
        mnuSobre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mnuSobre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mnuSobre.setMargin(new java.awt.Insets(10, 0, 0, 0));
        mnuSobre.setPreferredSize(new java.awt.Dimension(90, 40));
        mnuSobre.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jMenuBar1.add(mnuSobre);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuItemCadastroCondominioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuItemCadastroCondominioMouseClicked
        
        
        
    }//GEN-LAST:event_mnuItemCadastroCondominioMouseClicked

    private void mnuCondominioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuCondominioMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_mnuCondominioMouseClicked

    private void mnuItemCadastroCondominioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemCadastroCondominioActionPerformed
        // sub menu cadastro de condominio do menu condominio:
        ViewCadastroCondominio cadastroCondominio = new ViewCadastroCondominio();
        cadastroCondominio.setLocationRelativeTo(null);
        cadastroCondominio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mnuItemCadastroCondominioActionPerformed

    private void mnuItemCadastroUnidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemCadastroUnidadeActionPerformed
        // sub menu cadastro de unidade do menu condominio
        ViewCadastroUnidade unidade = new ViewCadastroUnidade();
        unidade.setLocationRelativeTo(null);
        unidade.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mnuItemCadastroUnidadeActionPerformed

    private void mnuItemCadastroCondominoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemCadastroCondominoActionPerformed
        // sub menu cadastro de condômino no menu condômino
        ViewCadastroCondomino condomino = new ViewCadastroCondomino();
        condomino.setLocationRelativeTo(null);
        condomino.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mnuItemCadastroCondominoActionPerformed

    private void mnuFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuFuncionarioActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_mnuFuncionarioActionPerformed

    private void mnuItemCadatroFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemCadatroFuncionarioActionPerformed
        // TODO add your handling code here:
        ViewCadastroFuncionario funcionario = new ViewCadastroFuncionario();
        funcionario.setLocationRelativeTo(null);
        funcionario.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mnuItemCadatroFuncionarioActionPerformed

    private void mnuCondominioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCondominioActionPerformed
        // 
        
    }//GEN-LAST:event_mnuCondominioActionPerformed

    private void mnuInquilinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuInquilinoActionPerformed
        
    }//GEN-LAST:event_mnuInquilinoActionPerformed

    private void mnuItemCadastroInquilinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemCadastroInquilinoActionPerformed
        // Menu Inquilino
        ViewCadastroInquilino inquilino = new ViewCadastroInquilino();
        inquilino.setLocationRelativeTo(null);
        inquilino.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mnuItemCadastroInquilinoActionPerformed

    private void mnuItemFuncRelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemFuncRelActionPerformed
        // TODO add your handling code here:
        ViewRelatorioFuncionario funcionario = new ViewRelatorioFuncionario();
        funcionario.setLocationRelativeTo(null);
        funcionario.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mnuItemFuncRelActionPerformed

    private void mnuItemPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemPerfilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuItemPerfilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPainelCentral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPainelCentral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPainelCentral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPainelCentral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewPainelCentral().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mnuCondominio;
    private javax.swing.JMenu mnuCondomino;
    private javax.swing.JMenu mnuConfiguracoes;
    private javax.swing.JMenu mnuFuncionario;
    private javax.swing.JMenu mnuInquilino;
    private javax.swing.JMenuItem mnuItemCadastroCondominio;
    private javax.swing.JMenuItem mnuItemCadastroCondomino;
    private javax.swing.JMenuItem mnuItemCadastroInquilino;
    private javax.swing.JMenuItem mnuItemCadastroUnidade;
    private javax.swing.JMenuItem mnuItemCadatroFuncionario;
    private javax.swing.JMenuItem mnuItemFuncRel;
    private javax.swing.JMenuItem mnuItemPerfil;
    private javax.swing.JMenu mnuRelatorio;
    private javax.swing.JMenu mnuSegurança;
    private javax.swing.JMenu mnuSobre;
    // End of variables declaration//GEN-END:variables
}
